// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * The `.gitattributes` scaffolds the mirror generates (§5.13, design §8.1/§8.4).
 *
 * There are two of them, and they exist for different reasons.
 *
 * The **root** file is repository policy. Nothing the mirror writes is allowed to
 * depend on the machine that checked it out, and `.gitattributes` is the only
 * place git lets that be stated: without `* text=auto eol=lf`, a Windows clone
 * applies `core.autocrlf` and every text file in the tree differs from the bytes
 * the writer produced — INV-1 broken by the checkout rather than by the sweep,
 * and invisible to every test in this package because every test agrees with
 * itself about line endings. `_derived/** linguist-generated` is the smaller
 * favour: INV-9 says those views are regenerated wholesale, so they move on every
 * sync, and a review of one genuinely changed business rule should not open on
 * four thousand lines of regenerated index.
 *
 * The **per-record** file (see `attachments.ts`, which calls
 * {@link buildAttachmentGitAttributes}) is how "attachments above the threshold
 * go to git-LFS" is expressed at all. git has no way to select a file by size:
 * a pattern matches by name or it does not match. So the size decision has to be
 * made where the bytes are — at write time, by the code that just measured them —
 * and then written down as a name pattern git can obey afterwards. That is the
 * only mechanism available; the alternative of asking the user to maintain the
 * patterns by hand is the failure this tool exists to remove.
 *
 * Why the LFS patterns live beside the attachments rather than in the root file:
 * a root file listing every large attachment on the instance (M16 measured 452 of
 * them) would be a file that every sweep of every table can dirty, that cannot be
 * written until the last table has been fetched, and that two people syncing two
 * different scopes conflict on. A file per record directory is written by the same
 * pass that writes the binaries, changes only when that record's attachments
 * change, and is deleted with the record.
 *
 * ## The two glob strings are spelled here, not imported
 *
 * `attachments/**` and `_derived/**` look like they should come from
 * `ATTACHMENTS_DIR_NAME` and `DERIVED_DIR_NAME`. They deliberately do not. This
 * module is the leaf that `attachments.ts` imports (the reverse edge would be a
 * cycle, which `no-circular` forbids), and reaching into `derived/` from `write/`
 * to borrow a string would point a dependency edge the wrong way for the sake of
 * one token. What is written below is also not quite those constants: it is a
 * *git pattern*, and the `/**` suffix carries meaning that a directory-name
 * constant does not have. The coupling is real all the same, so it is pinned by
 * assertion — `test/gitAttributes.test.ts` and `test/attachments.test.ts` each
 * compare a directive here against the constant it shadows, and renaming either
 * directory fails a test instead of silently un-marking a tree.
 */
import type { MirrorConfig } from "../contracts";
import { encodeUtf8 } from "../serialize/serializer";

import { atomicWriteFile } from "./atomicWrite";
import { toNativePath, type WriterFs } from "./fs";

/** Name of the file, at the repository root and inside attachment directories. */
export const GITATTRIBUTES_FILE_NAME = ".gitattributes";

/**
 * The attribute set that routes one path through git-LFS.
 *
 * The three filter attributes are what git's own LFS documentation prescribes;
 * `-text` is the fourth for a reason that is easy to lose: with it absent, an
 * `eol` setting inherited from the root pattern applies to the POINTER file's
 * content, and a pointer written with CRLF is a pointer git-LFS cannot resolve.
 */
export const LFS_ATTRIBUTES = "filter=lfs diff=lfs merge=lfs -text";

/** Git pattern for the derived views (shadows `derived/render.DERIVED_DIR_NAME`). */
const DERIVED_PATH_GLOB = "_derived/**";

/** Git pattern for attachment bytes (shadows `attachments.ATTACHMENTS_DIR_NAME`). */
const ATTACHMENT_PATH_GLOB = "attachments/**";

/**
 * Render a `.gitattributes` body from comment/directive pairs.
 *
 * Comments are part of the output on purpose: the generated repository is read by
 * humans who did not run the tool, and a bare `_derived/** linguist-generated`
 * with no explanation is a line someone eventually deletes because it looks like
 * noise. They are not part of the CONTRACT, though — the suites assert the
 * directive lines and ignore everything starting with `#`, so improving a sentence
 * here is not a test failure.
 */
function renderAttributesFile(
  stanzas: ReadonlyArray<{ why: readonly string[]; directive: string }>
): Uint8Array {
  const lines: string[] = [
    "# Generated by syncrona mirror. Edits are overwritten on the next run.",
  ];
  for (const stanza of stanzas) {
    lines.push("");
    for (const line of stanza.why) {
      lines.push(`# ${line}`);
    }
    lines.push(stanza.directive);
  }
  return encodeUtf8(`${lines.join("\n")}\n`);
}

/**
 * The repository-root scaffold (§5.13).
 *
 * A pure function of the config, so `mirror init` and a later `mirror sync` that
 * re-provisions produce the same bytes — nothing dated, nothing about the machine.
 *
 * The attachment stanza is omitted when attachments are disabled rather than
 * written unconditionally: the file is documentation as much as configuration, and
 * a rule about a directory this repository will never contain is a claim that it
 * might.
 */
export function buildRootGitAttributes(config: MirrorConfig): Uint8Array {
  const stanzas = [
    {
      why: [
        "Line endings are the mirror's, not the checkout's: a re-sync must produce",
        "the same bytes on every platform (INV-1).",
      ],
      directive: "* text=auto eol=lf",
    },
    {
      why: [
        "Regenerated wholesale from the shards on every sync, so it churns. Marking",
        "it keeps a review of a real change from being buried under it.",
      ],
      directive: `${DERIVED_PATH_GLOB} linguist-generated`,
    },
  ];
  if (config.attachments.enabled) {
    stanzas.push({
      why: [
        "Attachment bytes ARE the artifact. Normalizing line endings inside a PDF or",
        "a .xlsx is corruption, not tidying.",
      ],
      directive: `${ATTACHMENT_PATH_GLOB} -text`,
    });
  }
  return renderAttributesFile(stanzas);
}

/**
 * The per-record-directory scaffold: one LFS pattern per large attachment.
 *
 * The pattern is `<attachment sys_id>_*`, not the attachment's actual file name.
 * `.gitattributes` has no escaping syntax whatsoever, so a file name containing
 * `*`, `?` or `[` cannot be written as a literal pattern — it would match the
 * wrong files, or (the likelier and worse case) match nothing at all and leave a
 * 76 MB blob committed straight into the pack while the mirror reports it as
 * LFS-stored. A sys_id is 32 lowercase hex characters, guaranteed by INV-6 to
 * contain no glob metacharacter, and the `_` separator plus the uniqueness of the
 * sys_id means the pattern matches exactly the one file it is about.
 *
 * `sysIds` is expected already sorted by the caller — the sorted list is the same
 * one that goes into the shard entry, and sorting it twice invites the two orders
 * to drift.
 */
export function buildAttachmentGitAttributes(
  sysIds: readonly string[]
): Uint8Array {
  return renderAttributesFile([
    {
      why: [
        "These attachments are at or above the configured LFS threshold. The pattern",
        "matches on the sys_id prefix because git file names may contain glob",
        "metacharacters and this file has no way to escape them.",
      ],
      directive: sysIds.map((sysId) => `${sysId}_* ${LFS_ATTRIBUTES}`).join("\n"),
    },
  ]);
}

function bytesEqual(left: Uint8Array, right: Uint8Array): boolean {
  if (left.length !== right.length) {
    return false;
  }
  for (let index = 0; index < left.length; index += 1) {
    if (left[index] !== right[index]) {
      return false;
    }
  }
  return true;
}

/**
 * Put the root scaffold in place, replacing whatever is there.
 *
 * Generated, not merged: a `.gitattributes` that the tool half-owns is one nobody
 * can reason about, and the directives here are correctness rules rather than
 * preferences — a user who removed `eol=lf` did not express a preference, they
 * broke the tree for the next person on another platform. A repository that needs
 * extra attributes has `.gitattributes` files in subdirectories and
 * `info/attributes` for local-only rules, both of which git honours and neither of
 * which this touches.
 *
 * The read-and-compare before writing is not an optimization of the write itself
 * (one small file), it is about the mtime. `mirror init` is re-runnable and
 * `mirror sync` re-provisions, so an unconditional write would restamp a file at
 * the root of a possibly huge working tree on every invocation, and git's
 * fsmonitor and untracked-cache both key off exactly that.
 */
export async function provisionGitAttributes(
  fs: WriterFs,
  root: string,
  config: MirrorConfig
): Promise<void> {
  const desired = buildRootGitAttributes(config);
  const target = toNativePath(root, GITATTRIBUTES_FILE_NAME);
  const existing = await fs.readFile(target);
  if (existing !== null && bytesEqual(existing, desired)) {
    return;
  }
  await fs.makeDir(root);
  await atomicWriteFile(fs, target, desired);
}
