// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * The `.gitignore` that hides the mirror's own state directory (design §8.1,
 * architecture "`mirror init` scaffolds a `.gitignore` (checkpoint dir)").
 *
 * Everything under `.mirror/` is machine-local: the resume checkpoint, and — since
 * the reconcile cadence was wired — the run counter. Both are regenerable, both
 * differ between two clones of the same mirror, and both are written by the engine
 * rather than by the writer, so neither passes through the redactor and neither is
 * claimed by a shard. Committing them would make one machine's progress another
 * machine's history.
 *
 * ## Why the file lives inside `.mirror/` rather than at the repository root
 *
 * A root `.gitignore` is a file the user owns. The mirror would then be in the
 * business of merging into it — appending a stanza, recognising its own stanza on
 * the next run, not clobbering a line the operator added — which is the
 * half-ownership `provisionGitAttributes` explicitly refuses for `.gitattributes`.
 * A `.gitignore` inside the generated directory needs none of that: the mirror owns
 * the whole directory, the file is one line, and it can be written unconditionally
 * without ever touching something a human wrote.
 *
 * The single pattern is `*`, with no `!.gitignore` exception. Git applies a
 * directory's ignore file to that file too, so `*` makes the entire directory —
 * including this scaffold — invisible to `git status`, `git add -A` and every CI
 * wrapper that runs them. That is the property INV-1 needs: a second sync of an
 * unchanged instance must leave a clean working tree, and it cannot do that if the
 * run counter it just incremented is a tracked file, or even an untracked one that
 * `git add -A` would sweep up on the operator's behalf.
 *
 * ## Why the engine provisions it on every run, not `mirror init`
 *
 * `mirror init` creates a repository that has no `.mirror/` directory at all —
 * there is nothing to ignore until the first sync writes the first checkpoint. So
 * per-run provisioning is not merely equivalent to init-time provisioning, it is
 * the earliest correct moment. It also self-heals two cases init cannot reach: a
 * tree provisioned by an older build that predates this file, and a tree whose
 * `.mirror/` was deleted by hand to force a clean start.
 */
import { encodeUtf8 } from "../serialize/serializer";

import { atomicWriteFile } from "./atomicWrite";
import { toNativePath, type WriterFs } from "./fs";

import { CHECKPOINT_REL_PATH } from "./sweepProgress";

/**
 * The mirror's state directory, derived from the checkpoint path rather than
 * restated — the same reason `checkpoint.ts` derives its own directory. A §3 change
 * that renames `.mirror/` moves the ignore file with it, with no second edit to
 * forget and no window in which the counter is suddenly visible to git.
 */
const MIRROR_DIR_REL_PATH = CHECKPOINT_REL_PATH.slice(0, CHECKPOINT_REL_PATH.indexOf("/"));

/** Where the scaffold goes: inside the directory it hides. */
export const MIRROR_IGNORE_REL_PATH = `${MIRROR_DIR_REL_PATH}/.gitignore`;

/**
 * The scaffold's bytes — a pure function of nothing, so every run of every build
 * produces the same file and the read-and-compare below always short-circuits.
 */
export function buildMirrorGitIgnore(): Uint8Array {
  return encodeUtf8(
    [
      "# Generated by syncrona mirror. Edits are overwritten on the next run.",
      "",
      "# Resume and cadence state for THIS checkout: regenerable, machine-local, and",
      "# meaningless in anyone else's clone. The pattern covers this file too, so the",
      "# whole directory stays invisible to git rather than merely untracked.",
      "*",
    ].join("\n") + "\n"
  );
}

/**
 * Put the scaffold in place before anything else writes into `.mirror/`.
 *
 * The read-and-compare is `provisionGitAttributes`' reasoning applied to a smaller
 * file: not an optimization of the write, but of the mtime. Git's untracked cache
 * and fsmonitor both invalidate a directory whose contents were restamped, and this
 * directory is stat'ed on every `git status` the operator runs.
 */
export async function provisionMirrorGitIgnore(fs: WriterFs, root: string): Promise<void> {
  const desired = buildMirrorGitIgnore();
  const target = toNativePath(root, MIRROR_IGNORE_REL_PATH);
  const existing = await fs.readFile(target);
  if (existing !== null && bytesEqual(existing, desired)) {
    return;
  }
  await fs.makeDir(toNativePath(root, MIRROR_DIR_REL_PATH));
  await atomicWriteFile(fs, target, desired);
}

function bytesEqual(left: Uint8Array, right: Uint8Array): boolean {
  if (left.length !== right.length) {
    return false;
  }
  for (let index = 0; index < left.length; index += 1) {
    if (left[index] !== right[index]) {
      return false;
    }
  }
  return true;
}
