// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * Golden byte tests for the serializer (architecture §8, INV-1, INV-8).
 *
 * Every fixture is a hand-written pair: a Table API response fragment in, the
 * exact bytes the mirror must produce out. Nothing here is generated by the code
 * under test — a golden file produced by the implementation would only ever pin
 * the implementation against itself and would silently absorb the very format
 * drift INV-8 exists to catch.
 *
 * The comparison is on BYTES, not on parsed values. Two JSON documents can be
 * deeply equal and still differ in key order, indentation, trailing newline or
 * BOM, and all four of those are what makes a re-run of an unchanged instance
 * diff to nothing (INV-1). A `toEqual` on parsed objects would pass through all
 * of them.
 *
 * If one of these tests fails, the correct question is not "how do I update the
 * fixture" — it is "is this a format change?" A deliberate change to the emitted
 * bytes requires bumping `FORMAT_VERSION` and shipping a migration (INV-8); the
 * FORMAT_VERSION gate at the bottom of this file is here to make that step
 * impossible to forget.
 */
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { FORMAT_VERSION } from "../src/constants";
import type { FieldDescriptor, TableCatalogEntry } from "../src/contracts";
import {
  canonicalJsonBytes,
  encodeUtf8,
  serializeRow,
} from "../src/serialize/serializer";

const GOLDEN_ROOT = join(__dirname, "golden", "serializer");

/**
 * The compact fixture form. Only the fields a case actually exercises are
 * written; {@link buildCatalogEntry} fills in the rest of the §4.2 contract with
 * neutral defaults, so a fixture reads as "what this case is about" instead of
 * as forty lines of boilerplate per column.
 */
interface Fixture {
  description: string;
  table: { name: string; fields: Array<Partial<FieldDescriptor>> };
  row: Record<string, unknown>;
}

interface ExpectedSummary {
  sysId: string;
  table: string;
  extractedFiles: string[];
  parseFailures: string[];
}

const buildFieldDescriptor = (
  partial: Partial<FieldDescriptor>
): FieldDescriptor => ({
  element: partial.element ?? "",
  internalType: partial.internalType ?? "string",
  extractAs: partial.extractAs ?? null,
  isJsonBlob: partial.isJsonBlob ?? false,
  isNoise: partial.isNoise ?? false,
  isDenied: partial.isDenied ?? false,
  reference: partial.reference ?? null,
  maxLength: partial.maxLength ?? null,
});

const buildCatalogEntry = (fixture: Fixture): TableCatalogEntry => ({
  name: fixture.table.name,
  sysId: "00000000000000000000000000000000",
  superClass: null,
  isMetadata: true,
  tier: 1,
  rowCount: null,
  maxUpdatedOn: null,
  fields: fixture.table.fields.map(buildFieldDescriptor),
  status: "included",
});

const readJson = <T>(path: string): T => JSON.parse(readFileSync(path, "utf8")) as T;

/**
 * Compare two byte sequences, reporting a readable diff first.
 *
 * `Buffer.equals` gives a true/false with no context, which turns a one-character
 * ordering regression into an unreadable failure. Decoding first means the
 * assertion that usually fires shows the actual text diff; the byte assertion
 * that follows is what catches the differences decoding hides (a BOM, a CRLF, a
 * second trailing newline).
 */
const expectBytes = (actual: Uint8Array, expected: Buffer, what: string): void => {
  const actualBuffer = Buffer.from(actual);
  expect(`${what}:\n${actualBuffer.toString("utf8")}`).toBe(
    `${what}:\n${expected.toString("utf8")}`
  );
  expect(actualBuffer.equals(expected)).toBe(true);
};

const caseNames = readdirSync(GOLDEN_ROOT, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

describe("serializeRow golden fixtures", () => {
  it("discovers every fixture directory", () => {
    // A fixture that stops being executed is worse than no fixture: the suite
    // still looks green. Pin the count so deleting or misplacing a case is a
    // failure rather than a silent loss of coverage.
    expect(caseNames.length).toBe(10);
  });

  describe.each(caseNames)("%s", (caseName) => {
    const caseDir = join(GOLDEN_ROOT, caseName);
    const fixture = readJson<Fixture>(join(caseDir, "input.json"));
    const expectedSummary = readJson<ExpectedSummary>(
      join(caseDir, "summary.json")
    );

    it("states what it pins", () => {
      // Every fixture has to explain itself. A golden file whose intent is not
      // written down cannot be reviewed, and the reviewer is the only defence
      // against a fixture being "updated" to match a regression.
      expect(fixture.description.length).toBeGreaterThan(40);
    });

    it("emits the expected record.json bytes", () => {
      const record = serializeRow(fixture.row, buildCatalogEntry(fixture));
      expectBytes(
        canonicalJsonBytes(record.recordJsonValue),
        readFileSync(join(caseDir, "record.json")),
        `${caseName}/record.json`
      );
    });

    it("emits the expected extracted files, byte for byte", () => {
      const record = serializeRow(fixture.row, buildCatalogEntry(fixture));

      expect(record.extractedFiles.map((file) => file.fileName)).toEqual(
        expectedSummary.extractedFiles
      );

      for (const file of record.extractedFiles) {
        expectBytes(
          encodeUtf8(file.contents),
          readFileSync(join(caseDir, "files", file.fileName)),
          `${caseName}/files/${file.fileName}`
        );
      }
    });

    it("reports the expected identity and parse failures", () => {
      const record = serializeRow(fixture.row, buildCatalogEntry(fixture));
      expect(record.sysId).toBe(expectedSummary.sysId);
      expect(record.table).toBe(expectedSummary.table);
      expect(record.parseFailures).toEqual(expectedSummary.parseFailures);
    });

    it("obeys the §8 envelope rules regardless of content", () => {
      const record = serializeRow(fixture.row, buildCatalogEntry(fixture));
      const bytes = Buffer.from(canonicalJsonBytes(record.recordJsonValue));
      const text = bytes.toString("utf8");

      // No BOM: a leading U+FEFF encodes as EF BB BF and would make every file
      // differ from the byte-identical twin any other tool produces.
      expect(bytes.subarray(0, 3).equals(Buffer.from([0xef, 0xbb, 0xbf]))).toBe(
        false
      );
      // Exactly one trailing newline, and LF only — a CRLF anywhere in the
      // envelope would make the tree depend on the platform that wrote it.
      expect(text.endsWith("\n")).toBe(true);
      expect(text.endsWith("\n\n")).toBe(false);
      expect(text).not.toContain("\r");

      for (const file of record.extractedFiles) {
        expect(file.contents.endsWith("\n")).toBe(true);
      }
    });

    it("is byte-identical when serialized twice (INV-1)", () => {
      // The point of the mirror is that an unchanged instance produces an
      // unchanged tree. Two calls in the same process is the weakest possible
      // form of that promise, and it is still the one that catches accidental
      // shared mutable state — a memoized comparator, a reused accumulator, a
      // Set hoisted to module scope.
      const entry = buildCatalogEntry(fixture);
      const first = serializeRow(fixture.row, entry);
      const second = serializeRow(fixture.row, entry);

      expect(Buffer.from(canonicalJsonBytes(first.recordJsonValue))).toEqual(
        Buffer.from(canonicalJsonBytes(second.recordJsonValue))
      );
      expect(first.extractedFiles).toEqual(second.extractedFiles);
      expect(first.parseFailures).toEqual(second.parseFailures);
    });

    it("does not mutate the row it was given", () => {
      // The Fetcher hands the same page to more than one consumer, and a
      // serializer that edited its input in place would make the result depend
      // on call order — a purity violation (INV-7) that no single-call test can
      // see.
      const before = JSON.stringify(fixture.row);
      serializeRow(fixture.row, buildCatalogEntry(fixture));
      expect(JSON.stringify(fixture.row)).toBe(before);
    });
  });

  it("pins the fixtures to a format version (INV-8)", () => {
    // The fixtures describe format version N. If someone changes the emitted
    // bytes and updates the fixtures to match, this file must be updated too —
    // and updating it is the moment they are forced to notice that INV-8 also
    // demands a `FORMAT_VERSION` bump and a migration for every mirror already
    // on disk.
    const pinned = Number(
      readFileSync(join(GOLDEN_ROOT, "FORMAT_VERSION"), "utf8").trim()
    );
    expect(pinned).toBe(FORMAT_VERSION);
  });
});
